### ISSUE TITLE
[window-chrome-2880px-로그인 페이지] 로그인 페이지 CSS 관련 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-stella-choi-community-fe#55]
**버그 설명**
이메일 입력과 비밀번호 아래 부분의 CSS가 다릅니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인 페이지 이동
2. 이메일 입력 후 비밀번호 입력

**예상한 동작**
CSS의 width 선이 동일할 것이라고 생각했습니다.

**스크린샷**
<img width="449" alt="image" src="https://github.com/user-attachments/assets/e5beaf28-c68b-40c1-accc-7701b90dee67" />

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**

**Comment by choiyoorim** [comment]
오! 정꾸 ㅎㅎ QA 감사합니다!!!! 열심히 고쳐볼게요

**Comment by choiyoorim** [comment]
#54 다른 문제 수정할 때 같이 수정했던 내용이라, 따로 추가 수정은 하지 않겠습니다!
